services:
  identity-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5011;http://+:5010"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Identity.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Identity.API.pfx:/home/app/.aspnet/https/Identity.API.pfx:ro